### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Reimnop** [ExtraFrisky/Byebye-Bby#1]
Oh my god I've just been scammed and hacked by those fuckers at bby.rip, thank you for exposing them, this should be way more popular than this.

**Comment by ExtraFrisky** [comment]
Thank you for the feedback!

Be sure to raise your issue with Discord Support. They're pretty good about giving stolen accounts back.

**Comment by Reimnop** [comment]
> They're pretty good about giving stolen accounts back.

Is this sarcastic? I opened my ticket 11 days ago and still haven't gotten a response.

**Comment by Reimnop** [comment]
Also bby[.]rip is now down rendering BbyStealer useless unless they update and redistribute it to hundreds of scammers .

**Comment by ExtraFrisky** [comment]
@Reimnop they have been pretty good, sadly that doesn't mean all cases. :( 

I have seen instances where accounts were returned within 24 hours. Other cases might just be tricky based on number of opened tickets... Discord support are very busy right now, they're actively dropping the ball on many tickets. :/

**Comment by ExtraFrisky** [comment]
Closing
