### ISSUE TITLE
They are all stupids

### ISSUE THREAD

**Issue by JimmyGaubert** [ExtraFrisky/Byebye-Bby#3]
They are all stupids, At least as much as me, who really believed that I was going to help a video-game creator.
I'm a web dev with 127 IQ (and some autistic traits) but I am a sensitive person who likes to help people... with my bots.

This repository tells only the truth. I had a badge (certified bot developer). The kids who made me launch the grabber didn't had my Discord account. He gave me back my steam and my paypal because he was gullible enough to believe that I would give him the badge if I could get the account back (with the help of the Discord support) lulz.

I'm sorry for the customers of bby, but i'm not sorry, you are very stupid too. 
You could create your own stuff instead of losing 250$, it's super easy,
so easy that this stupid brunxkd and this stupid c0lzia could do it. 
You could also not scam people, it would be even easier.

![p1](https://user-images.githubusercontent.com/63388059/152703158-43aab23e-d64a-44d8-a7f4-aee2104aac7f.png)

brunxkd saying bullshit to the kid who thought he could steal my discord account with their grabber :

![unknown5](https://user-images.githubusercontent.com/63388059/152703280-423730de-24dd-4322-b2b4-3f7b8bc46cda.png)
![6](https://user-images.githubusercontent.com/63388059/152703214-15136df0-d4cd-4cb6-853c-b1867820e520.png)
![unknown](https://user-images.githubusercontent.com/63388059/152703252-419c5e7e-ae1c-4e61-ab2e-7756d3b4eeef.png)
![unknown3](https://user-images.githubusercontent.com/63388059/152703272-5f639cf6-6b66-4b35-9c2c-8c195473061b.png)

Stop scamming people.
Fuck you brunxkd, fuck you c0lzia, fuck you customers.
Thank you again ExtraFrisky for this repository.
Dear visitor, star this repo please.

**Comment by ExtraFrisky** [comment]
@JimmyGaubert Well said! Thank you for your comments and screenshots!

**Comment by ExtraFrisky** [comment]
Closing
